node {
    def server = Artifactory.server('imambux.jfrog.io')
    def rtMaven = Artifactory.newMavenBuild()
    def buildInfo = Artifactory.newBuildInfo()
    stage 'Build'
        git url: 'https://github.com/imambux/gs-maven.git'

    stage 'Artifactory configuration'
        rtMaven.tool = 'maven' // Tool name from Jenkins configuration
        rtMaven.deployer repo:'ibm-dev-local',  server: server
        rtMaven.resolver repo:'ibm-dev', server: server

        stage('Config Build Info') {
            buildInfo.env.capture = true
            buildInfo.env.filter.addInclude("*")
        }

        stage('Extra Maven configurations') {
            rtMaven.usesPlugin = true // Artifactory plugin already defined in build script
        }
        stage('Exec Maven') {
            rtMaven.run rootDir: "artifactory/", buildFile: 'pom.xml', tasks: 'clean publish', buildInfo: buildInfo
        }
        stage('Publish build info') {
            server.publishBuildInfo buildInfo
        }
}
